astra_django/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('qa_app.urls')),
    path('datasets/', include('data_sets.urls'))
]

data_sets/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, show, create, create_data_set
app_name = "data_set"
urlpatterns = [
    path('', index, name="index"),
    path('create/', create, name="create"),
    path('create_data_set/', create_data_set, name="create_data_set"),
    path('show/<int:pk>/', show, name="show"),


]

qa_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, submit_question
# app_name = "cnn_daily"
urlpatterns = [
    path('', index, name="index"),
    path('submit/', submit_question, name="submit_question"),

]

data_sets/models.py
from django.db import models

class DataSet(models.Model):
    name = models.CharField(max_length=250)
    def __str__(self):
        return f"{self.name}"
    

class Data(models.Model):
    data_set = models.ForeignKey(DataSet, on_delete=models.CASCADE)
    description = models.CharField(max_length=250)
    content = models.TextField()
    def __str__(self):
        return f"{self.data_set.name} : {self.description}"

qa_app/models.py
from django.db import models
from cassandra.cqlengine import columns
from django_cassandra_engine.models import DjangoCassandraModel

class CnnVectors(DjangoCassandraModel):
    __keyspace__ = "vector_db_keyspace"

    row_id = columns.Text(primary_key=True)
    attributes_blob = columns.Text()
    body_blob = columns.Text()
    vector = columns.Text()

class Answers(DjangoCassandraModel):
    __keyspace__ = "vector_db_keyspace"

    row_id = columns.UUID(primary_key=True)
    session_id = columns.Integer(index=True)
    question = columns.Text()
    answer = columns.Text()
# python manage.py sync_cassandra

# USE vector_sb_keyspace
# DESCRIBE TABLE answers
# SELECT * from answers;

qa_app/forms.py
from django import forms

data_sets/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from .models import DataSet, Data
def index(request):
    context = {}
    return render(request=request, template_name='data_sets/index.html', context=context)




def create(request):
    context = {}
    return render(request=request, template_name='data_sets/create.html', context=context)

@require_POST
def create_data_set(request):
    dataset = DataSet.objects.create(name=request.POST['dataset'],)
    
    return redirect('data_set:show', pk=dataset.pk)
    

def show(request, pk):
    context = {}
    return render(request=request, template_name='data_sets/show.html', context=context)

qa_app/views.py
from django.shortcuts import render
from uuid import uuid4
from .models import CnnVectors, Answers
from django.views.decorators.http import require_POST
from .question_answering import run_retrieval_qa_pipeline


def index(request):
    articles = CnnVectors.objects.all()
    context = {'articles' : articles}
    return render(request=request, template_name="index.html", context=context)


@require_POST
def submit_question(request):
    prompt = request.POST.get("prompt")
    instruction = request.POST.get("qa-instructions")
    answer = run_retrieval_qa_pipeline(prompt, instruction)
    Answers.objects.create(row_id=uuid4(), question=prompt, answer=answer)
    context = { 'question' :  prompt, 'answer' : answer}
    return render(request=request, template_name="answer.html", context=context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django + AstraDB App</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>
<body>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

templates/data_sets/create.html
{% include "base.html" %}

{% block content %}
<form method="POST" action="{% url 'data_set:create_data_set' %}">
    {% csrf_token %}

    <div class="mb-3">
        <label for="dataset" class="form-label">*Enter data set name</label>
        <input id="dataset" name="dataset" class="form-control"/>
    </div>



    <button type="submit" class="btn btn-primary">Submit</button>

</form>

{% endblock content %}

templates/data_sets/index.html
{% include "base.html" %}

{% block content %}
<div class="row">
<div class="col-8">
    <ul class="list-group">

<li class="list-group-item">


 
</li>

</ul>
</div>

<div class="col-4 ml-4">

</div>
</div> 



{% endblock content %}

templates/data_sets/show.html
{% include "base.html" %}

{% block content %}
<div class="row">
<div class="col-8">
    <ul class="list-group">

<li class="list-group-item">


 
</li>

</ul>
</div>

<div class="col-4 ml-4">
    <form method="POST" action="{% url 'data_set:create' %}">
        {% csrf_token %}

        <div class="mb-3">
            <label for="dataset" class="form-label">*Enter your query:</label>
            <input id="dataset" name="dataset" class="form-control"/>
        </div>



        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>
</div> 



{% endblock content %}

templates/qa_app/answer.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <p class="p-4 bg-secondary">{{ question }}</p>

        <p class="p-4 fst-italic">{{ answer }}</p>
    

        <a href="{% url 'index' %}">Back to articles</a>
    </div>
</div>

{% endblock %}

templates/qa_app/index.html
{% include "base.html" %}

{% block content %}
<div class="row">
<div class="col-8">
    <ul class="list-group">
{% for article in articles %} 
<li class="list-group-item">
<h1 class="text-success">Article #{{ forloop.counter }}</h1>
 <p class="fw-light">{{ article.body_blob }}</p>
 
</li>
{% endfor %}
</ul>
</div>

<div class="col-4 ml-4">
    <form method="POST" action="{% url 'submit_question' %}">
        {% csrf_token %}

        <div class="mb-3">
            <label for="qa-prompt" class="form-label">*Enter your query:</label>
            <textarea id="qa-prompt" name="prompt" class="form-control" rows="4" required></textarea>
        </div>

		<div class="mb-3">
            <label for="qa-instructions" class="form-label">
                Enter any instructions for customizing your answer.</br>
                <em>For example: "Answer in Italian"</em>
            </label>
            <textarea id="qa-instructions" name="qa-instructions" class="form-control" rows="2"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>

    </form>
</div>
</div> 



{% endblock content %}